# Generated by Django 4.1.1 on 2022-09-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0002_rename_fecha_nacimianto_autor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_libros.autor'),
        ),
    ]
